# Generated by Django 4.1.3 on 2022-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='long_name',
            field=models.URLField(max_length=255),
        ),
    ]
